[workspace]
members = [
    "contracts/crowdfunding",
    "contracts/counter",
    "contracts/abstract_account",
    "contracts/private_voting",
    "https://github.com/AztecProtocol/aztec-packages/tree/master/noir-projects/noir-contracts/contracts/token_contract"
]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.72.1", directory="noir-projects/aztec-nr/aztec" }
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.72.1", directory="noir-projects/aztec-nr/value-note"}
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.72.1", directory="noir-projects/noir-contracts/contracts/token_contract" }
router = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.72.1", directory="noir-projects/noir-contracts/contracts/router_contract" }
